config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  resources :articles

   root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    @article.save
    redirect_to @article
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy


    redirect_to articles_path
  end

  def delete_all
    @article = Article.delete_all
    redirect_to articles_path
  end


  private
  def article_params
    params.require(:article).permit(:title, :text, :date, :summa,
                                    :predoplata, :ostatok, :cena_yst, :zamer,
                                    :postavshik, :profile, :comments, :number, :cena_postavhika, :m2,
                                    :cena_konstrukciu, :oplata, :dopu, :oplataOST, :oplataPR, :polPR,
                                    :polOST, :polSUM, :dop0, :color,
                                    :razm0,
                                    :kol0,

                                    :dop1,
                                    :razm1,
                                    :kol1,

                                    :dop2,
                                    :razm2,
                                    :kol2,

                                    :dop3,
                                    :razm3,
                                    :kol3,

                                    :dop4,
                                    :razm4,
                                    :kol4,

                                    :dop5,
                                    :razm5,
                                    :kol5,

                                    :dop6,
                                    :razm6,
                                    :kol6,

                                    :dop7,
                                    :razm7,
                                    :kol7,

                                    :dop8,
                                    :razm8,
                                    :kol8,

                                    :dop9,
                                    :razm9,
                                    :kol9,

                                    :dop10,
                                    :razm10,
                                    :kol10,

                                    :dop11,
                                    :razm11,
                                    :kol11,

                                    :dop12,
                                    :razm12,
                                    :kol12,

                                    :dop13,
                                    :razm13,
                                    :kol13,

                                    :dop14,
                                    :razm14,
                                    :kol14,

                                    :dop15,
                                    :razm15,
                                    :kol15,

                                    :dop16,
                                    :razm16,
                                    :kol16,

                                    :dop17,
                                    :razm17,
                                    :kol17,

                                    :dop18,
                                    :razm18,
                                    :kol18,

                                    :dop19,
                                    :razm19,
                                    :kol19,

                                    :dop20,
                                    :razm20,
                                    :kol20,
                                    :color1,

                                    :color2,

                                    :color3,

                                    :color4,

                                    :color5,

                                    :color6,

                                    :color7,

                                    :color8,

                                    :color9,

                                    :color10,

                                    :color11,

                                    :color12,

                                    :color13,

                                    :color14,

                                    :color15,

                                    :color16,

                                    :color17,

                                    :color18,

                                    :color19,

                                    :color20
    )
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<center>
<h1>Изменить клиента</h1>


  <%= render 'form' %>
</center>

app/views/articles/index.html.erb
<html>
<head>

</head>
<style>

  .table_col {
    font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
    font-size: 14px;
    width: 1400px;
    background: white;
    text-align: center;
    border-collapse: collapse;
    color: #3E4347;
  }

  .table_col th:first-child, .table_col td:first-child {
    color: #8b8e91;
    border-left: none;
    background: aqua;
  }

  .table_col th {
    font-weight: normal;
    border-bottom: 2px solid #F5E1A6;
    border-right: 10px solid white;
    border-left: 10px solid white;
    padding: 8px 10px;
  }

  .table_col td {
    border-right: 10px solid white;
    border-left: 10px solid white;
    padding: 12px 10px;
    color: #8b8e91;
  }

</style>
<body>

<center>


  <h1>База клиентов</h1>

  <%= link_to 'Новый клиент', new_article_path %>
  <table class="table_col">

    <tr>
      <th>№ заказа</th>
      <th>ФИО</th>
      <th>Адрес</th>
      <th>Дата установки</th>

    </tr>

    <%  @articles.each do |article| %>
        <tr>

          <td><%= article.number %></td>
          <td><%= article.title %></td>
          <td><%= article.text %></td>
          <td><%= article.date %></td>

          <td> <%= link_to 'Просмотр', article_path(article) %>
            <%= link_to 'Изменить', edit_article_path(article) %>
            <%= link_to 'Удалить', article_path(article),
                        method: :delete,
                        data: {confirm: 'Are you sure?'} %></td>


        </tr>


    <% end %>


  </table>
</center>
</body>
</html>

app/views/articles/new.html.erb
<center>
<h1>Новый клиент</h1>
<%= render 'form' %>
</center>

app/views/articles/show.html.erb
<style>


  .table_col {
    font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
    font-size: 14px;
    width: 40%;
    background: white;
    text-align: center;
    border-collapse: separate;
    color: #3E4347;
  }

  .table_col th:first-child, .table_col td:first-child {
    width: 50px;
    color: #8b8e91;
    border-left: none;
    background: aqua;
  }

  .table_col th {
    font-weight: normal;
    border-bottom: 2px solid #F5E1A6;
    border-right: 10px solid white;
    border-left: 10px solid white;
    padding: 8px 10px;
  }

  .table_col td {
    border-right: 10px solid white;
    border-left: 10px solid white;
    padding: 12px 10px;
    color: #8b8e91;
  }

  .table_col tr {
    border-color: #2E2F30;
  }

</style>

<table align="left" class="table_col" border="1">
  <tr>
    <td>Номер заказа</td>
    <td> <%= @article.number %></td>
  </tr>
  <tr>
    <td>ФИО</td>
    <td> <%= @article.title %></td>
  </tr>
  <tr>
    <td>Адресс</td>
    <td>    <%= @article.text %></td>
  </tr>
  <tr>
    <td>Дата установки</td>
    <td>    <%= @article.date %></td>
  </tr>
  <tr>
    <td>Стоимость</td>
    <td><%= @article.summa %> [<%= @article.oplata %>] закрыл(a) заказ <%= @article.polSUM %> </td>
  </tr>
  <tr>
    <td>Предоплата</td>
    <td> <%= @article.predoplata %>   [<%= @article.oplataPR %>] принял(a) <%= @article.polPR %></td>
  </tr>
  <tr>
    <td>Остаток</td>
    <td><%= @article.ostatok %> [<%= @article.oplataOST %>] принял(a) <%= @article.polOST %></td>
  </tr>
  <tr>
    <td>Стоимость установки</td>
    <td> <%= @article.cena_yst %></td>
  </tr>
</table>
<table align="right" class="table_col" border="1">
  <tr>
    <td>Замер</td>
    <td><%= @article.zamer %></td>
  </tr>
  <tr>
    <td>Диллер</td>
    <td> <%= @article.postavshik %></td>
  </tr>
  <tr>
    <td>Цена поставщика</td>
    <td> <%= @article.cena_postavhika %></td>
  </tr>
  <tr>
    <td>Профиль</td>
    <td><%= @article.profile %></td>
  </tr>
  <tr>
    <td>Площадь конструкций</td>
    <td><%= @article.m2 %></td>
  </tr>
  <tr>
    <td>Стоимость конструкций</td>
    <td><%= @article.cena_konstrukciu %></td>
  </tr>
  <tr>
    <td>Коментарии</td>
    <td><%= @article.comments %></td>

  </tr>
  <tr>
    <td>Допы</td>
    <td align="left">


      <p></p><%= @article.dop0 %> <%= @article.razm0 %> <%= @article.color %>  <%= @article.kol0 %>
      <p></p> <%= @article.dop1 %> <%= @article.razm1 %> <%= @article.color1 %>  <%= @article.kol1 %>
      <p></p><%= @article.dop2 %> <%= @article.razm2 %> <%= @article.color2 %>  <%= @article.kol2 %>
      <p></p><%= @article.dop3 %> <%= @article.razm3 %> <%= @article.color3 %>  <%= @article.kol3 %>
      <p></p><%= @article.dop4 %> <%= @article.razm4 %> <%= @article.color4 %>  <%= @article.kol4 %>
      <p></p><%= @article.dop5 %> <%= @article.razm5 %> <%= @article.color5 %>  <%= @article.kol5 %>
      <p></p><%= @article.dop6 %> <%= @article.razm6 %> <%= @article.color6 %>  <%= @article.kol6 %>
      <p></p><%= @article.dop7 %> <%= @article.razm7 %> <%= @article.color7 %>  <%= @article.kol7 %>
      <p></p><%= @article.dop8 %> <%= @article.razm8 %> <%= @article.color8 %>  <%= @article.kol8 %>
      <p></p><%= @article.dop9 %> <%= @article.razm9 %> <%= @article.color9 %>  <%= @article.kol9 %>
      <p></p><%= @article.dop10 %> <%= @article.razm10 %> <%= @article.color10 %>  <%= @article.kol10 %>
      <p></p><%= @article.dop11 %> <%= @article.razm11 %> <%= @article.color11 %>  <%= @article.kol11 %>
      <p></p><%= @article.dop12 %> <%= @article.razm12 %> <%= @article.color12 %>  <%= @article.kol12 %>
      <p></p><%= @article.dop13 %> <%= @article.razm13 %> <%= @article.color13 %>  <%= @article.kol13 %>
      <p></p><%= @article.dop14 %> <%= @article.razm14 %> <%= @article.color14 %>  <%= @article.kol14 %>
      <p></p><%= @article.dop15 %> <%= @article.razm15 %> <%= @article.color15 %>  <%= @article.kol15 %>
      <p></p><%= @article.dop16 %> <%= @article.razm16 %> <%= @article.color16 %>  <%= @article.kol16 %>
      <p></p><%= @article.dop17 %> <%= @article.razm17 %> <%= @article.color17 %>  <%= @article.kol17 %>
      <p></p><%= @article.dop18 %> <%= @article.razm18 %> <%= @article.color18 %>  <%= @article.kol18 %>
      <p></p><%= @article.dop19 %> <%= @article.razm19 %> <%= @article.color19 %>  <%= @article.kol19 %>
      <p></p><%= @article.dop20 %> <%= @article.razm20 %> <%= @article.color20 %>  <%= @article.kol20 %>


    </td>
  </tr>

</table>
<div align="center">
  <p><%= link_to 'На главную', articles_path %></p>
  <p></p>
  <%= link_to 'Изменить', edit_article_path %></div>




app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myClients</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>myClients</h1>
<%= link_to 'База клиентов', controller: 'articles' %>